#!/usr/bin/env bash
#display the contents of the file /etc/passwd, using the while loop
while IFS=: read -r USERNAME PASSWORD USERID GID USERINFO HOMEDIR COMMAND
do
	echo "The user $USERNAME is part of the $GID gang,
		lives in $HOMEDIR and rides $COMMAND
		$USERID's place is protected by the passcode $PASSWORD,
		more info about the user here: $USERINFO"
done < /etc/passwd
