#!/usr/bin/env bash
#display the contents of the file /etc/passwd, using the while loop
while IFS=: read -r USERNAME PASSWPRD UID GID INFO HOME SHELL; do
	echo "The user $USERNAME is part of the $GID gang,
		lives in $HOME and rides $SHELL.
		$UID's place is protected by the passcode $PASSWORD,
		more info about the user here: $INFO"
done < /etc/passwd
