#!/usr/bin/env bash
#displays the time for 12 Hours and 59 minutes
#display Hours 0 to 12
#display minutes from 1 to 59
Hour=0

while [ $Hour -le 12 ]
do echo "hour: $Hour"
minute=1 
while [ $minute -le 59 ]
do echo "$minute"
	(( minute++ ))
done
(( Hour ++ ))
done 
