#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
#display hours 0 to 12
#display minutes from 1 to 59

for hour in {0..12}; do

	  echo "Hour: $hour"

	    for minute in {1..59}; do

		        echo $minute

			  done

		  done
