#!/usr/bin/env bash
#Make a copy of your 6-stop_me_if_you_can script, name it 67-stop_me_if_you_can.

trap "echo I am invincible!!!" SIGTERM
x=1
while [ "$x -gt 0 ]
do
	echo "To infinity and beyond"
	x=$((x+1))
	sleep 2
done
